export const RAMP_HOST_API_KEY = process.env.REACT_APP_RAMP_HOST_API_KEY;
export const PAYTRIE_PARTNER_URL = process.env.REACT_APP_PAYTRIE_PARTNER_URL;
export const TRANSAK_API_KEY = process.env.REACT_APP_TRANSAK_API_KEY;
export const TRANSAK_ENV = process.env.REACT_APP_TRANSAK_ENV;
export const ZAPPER_API_KEY = process.env.REACT_APP_ZAPPER_API_KEY;
export const ZAPPER_API_ENDPOINT = process.env.REACT_APP_ZAPPER_API_ENDPOINT;
export const SUSHI_SWAP_FRAME = process.env.REACT_APP_SUSHI_SWAP_FRAME_URL;
export const VELCRO_API_ENDPOINT = process.env.REACT_APP_VELCRO_API_ENDPOINT;