name: Build & deploy Dapp catalog staging

on:
  push:
    branches:
      - dapp-catalog
  pull_request:
    branches:
      - dapp-catalog

jobs:
  build_and_deploy:
    name: Build and Deploy dapp catalog
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: npm ci --no-audit
    
    - name: Build project
      run: npm run build

    - name: Deploy gh-pages (dapp catalog)
      if: github.ref == 'refs/heads/dapp-catalog'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: ./dappcatalog
        cname: wallet.ambire.com