name: Build & deploy ethpow

on:
  push:
    branches:
      - ethpow
  pull_request:
    branches:
      - ethpow

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      env:
        REACT_APP_RELAYRLESS: true
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      env:
        REACT_APP_RELAYRLESS: true
      run: npm ci
    
    - name: Build project
      env:
          REACT_APP_RELAYRLESS: true
      run: npm run build
    
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      env:
        REACT_APP_RELAYRLESS: true
      with:
        name: production-files
        path: ./build
  deploy-ethpow:
    name: Deploy ethpow
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ethpow'
    steps:
    - name: Download artifact
      env:
          REACT_APP_RELAYRLESS: true
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      env:
        REACT_APP_RELAYRLESS: true
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: ./ethpow
        cname: wallet.ambire.com
