name: Build & deploy ambire-bookmarklet-hook

on:
  push:
    branches:
      - ambire-bookmarklet-hook
  pull_request:
    branches:
      - ambire-bookmarklet-hook

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build
  deploy-extension:
    name: Deploy ambire-bookmarklet-hook
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/ambire-bookmarklet-hook'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: ./extension
        cname: wallet.ambire.com
