name: Build & deploy Paper backup staging

on:
  push:
    branches:
      - paper-backup
  pull_request:
    branches:
      - paper-backup

jobs:
  build_and_deploy:
    name: Build and Deploy dapp catalog
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Install NPM packages
      run: npm ci --no-audit

    - name: Build project
      run: npm run build

    - name: Deploy gh-pages (paper backup)
      if: github.ref == 'refs/heads/paper-backup'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        destination_dir: ./paperbackup
        cname: wallet.ambire.com
