name: Build & deploy 🔥 Ambire Wallet 🔥 (gnosis-portfolio 🧪🔬)

on:
  push:
    branches:
      - gnosis-portfolio
  pull_request:
    branches:
      - gnosis-portfolio
permissions:
  contents: write
jobs:
  build:
    name: Build & Deploy - (gnosis-portfolio 🧪🔬)
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }} 
    steps:
    - name: Checkout code 🛎️
      uses: actions/checkout@v3

    - name: Install Node.js ⚙️
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install NPM packages ♾️🕳️
      run: npm ci

    - name: Build project 🛠️
      run: npm run build

    - name: Deploy 🚀🌕 (gnosis-portfolio🧪🔬)
      if: github.ref == 'refs/heads/gnosis-portfolio'
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        folder: build
        target-folder: swap-gnosis-portfolio
        cname: wallet.ambire.com